# Generated by Django 5.0.7 on 2024-10-21 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100)),
                ('puertos', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGrabacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dias_grabacion', models.PositiveIntegerField()),
                ('verificacion_am', models.BooleanField(default=False)),
                ('verificacion_pm', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='aplicacion_camara.dvr')),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puerto', models.PositiveIntegerField()),
                ('dvr_nombre', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='aplicacion_camara.dvr')),
            ],
            options={
                'unique_together': {('dvr', 'puerto')},
            },
        ),
    ]
